## Numpy 실습 튜토리얼





In [18]:
import numpy as np
import pandas as pd
import seaborn as sns

print(np.__version__)
print(pd.__version__)
print(sns.__version__)

1.23.5
1.5.3
0.12.2


## Numpy 배열 ndaaray 객체로 되어있다.

In [ ]:
arr = [1,2,3,4,5]
print(arr)
a = np.array(arr)
print(a)
print(type(arr))
print(type(a))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


## Numpy 배열은 각 요소가 같은 타입을 가져야 함


In [ ]:
arr = [1,"A",3.14]
arr

[1, 'A', 3.14]

In [ ]:
new_arr = np.array(arr)
new_arr

array(['1', 'A', '3.14'], dtype='<U32')

In [ ]:
arr = [1,2,3,4,5]
arr = np.array(arr)
arr.shape


(5,)

In [36]:
arr = np.array([[[1,2,3]],
   [[1,2,3]],
    [[1,2,3]]])
print(arr.shape)

(3, 1, 3)


## 배열 생성 함수

### arange 함수

In [40]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
arr = np.arange(12).reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [47]:
b = np.zeros_like(arr)
b

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [50]:
b = b.reshape(-1)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
b = b.reshape(4,-1)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 인덱싱, 슬라이싱
- 인덱싱을 하면 차원이 줄어듬
- 슬라이싱은 차원이 보존됨

In [57]:
b[3]

array([0, 0, 0])

In [61]:
a = np.arange(12)
a[2:5]
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
a = a.reshape(3,4)

In [66]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a[1][1]

5

In [70]:
a[1,1]

5

In [71]:
a[1,2:] # 2차원 데이터가 1차원으로 줄음

array([6, 7])

In [72]:
a[1:,2:]

array([[ 6,  7],
       [10, 11]])

## Fancy Indexing

In [73]:
a[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [74]:
a[[2,0]]

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

## Boolean Indexing

In [75]:
a = np.arange(5)

b = [True,False,False,False,False]

a[b]

array([0])

In [76]:
a > 2

array([False, False, False,  True,  True])

In [77]:
a[a>2]

array([3, 4])

## 브로드캐스팅 (Broad Casting)

In [82]:
a = np.array([3,4,5])
a = a + np.array([1])
a

array([4, 5, 6])

In [84]:
x = np.arange(6).reshape(3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

## 배열 합치기

* stack (axis 개수가 증가함)
* concatenate (aixs가 유지)

In [86]:
X = np.array([[1,1],[2,2]])
X

array([[1, 1],
       [2, 2]])

In [88]:
Y = np.array([[3,3],[4,4]])
Y

array([[3, 3],
       [4, 4]])

In [92]:
np.concatenate((X,Y))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [94]:
np.concatenate((X,Y),axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [93]:
np.stack((X,Y))

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

In [97]:
np.stack((X,Y),axis=1)

array([[[1, 1],
        [3, 3]],

       [[2, 2],
        [4, 4]]])